import Navbar from "../components/Navbar"
import Head from 'next/head'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Dan's Examples</title>
        <meta name="description" content="generated by next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
    </div>
    
    
  )
}
